version: '2.0'

services:
  node1.onezone:
    restart: always
    # IMPORTANT when upgrading to 18.07.0 or later:
    # Remeber to update super groups in auth/saml configs,
    # as their format was changed to a list rather than binary with slashes
    image: docker.onedata.org/onezone:ID-4f301bc62f  # 18.02.0-rc8 + SAML rollover
    container_name: onezone-1
    hostname: node1.onezone.local
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Database persistence
      - "/home/ubuntu/volume/home/ubuntu/volumes/persistence:/volumes/persistence"
      # Server SSL certificates
      - "/home/ubuntu/volume/home/ubuntu/volumes/web_certs/web_key.pem:/etc/oz_panel/certs/web_key.pem"
      - "/home/ubuntu/volume/home/ubuntu/volumes/web_certs/web_cert.pem:/etc/oz_panel/certs/web_cert.pem"
      - "/home/ubuntu/volume/home/ubuntu/volumes/web_certs/web_chain.pem:/etc/oz_panel/certs/web_chain.pem"
      # SAML SSL certificates
      - "/home/ubuntu/volume/home/ubuntu/volumes/saml_certs/saml_key.pem:/etc/oz_worker/certs/saml_key.pem"
      - "/home/ubuntu/volume/home/ubuntu/volumes/saml_certs/saml_cert.pem:/etc/oz_worker/certs/saml_cert.pem"
      # OpenID, SAML and env config
      - "/home/ubuntu/volume/home/ubuntu/volumes/configs/auth.config:/etc/oz_worker/auth.config"
      - "/home/ubuntu/volume/home/ubuntu/volumes/configs/saml.config:/etc/oz_worker/saml.config"
      - "/home/ubuntu/volume/home/ubuntu/volumes/configs/overlay.config:/etc/oz_worker/overlay.config"
    ports:
      - "53:53"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      # Temporary expose for compatibility with 18.02.0-beta1 Oneproviders
      - "6666:6666"
      - "9443:9443"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_LOG_LEVEL: "none"
      ONEPANEL_BATCH_MODE: "true"

      # If enabled, a new web cert will be generated with CN matching the
      #   ONEPANEL_GENERATED_CERT_DOMAIN and signed by OnedataTestWebServerCa
      # NOTE: The generation will be performed upon every startup, any
      #   existing certs will be backed up and placed in the same directory.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_GENERATE_TEST_WEB_CERT: "false"  # default: false
      # The generated test web cert will be issued for below domain.
      ONEPANEL_GENERATED_CERT_DOMAIN: ""  # default: ""
      # If enabled, onepanel will trust any server that has a cert signed by
      #   the OnedataTestWebServerCa.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_TRUST_TEST_CA: "false"  # default: false

      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone.local"
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
        onezone:
          name: "OTC HNSC"
          domainName: "onedata.hnsc.otc-service.com"
        onepanel:
          users:
            "admin":
              password: "${ADMIN_PASSWORD}"
              userRole: "admin"
